steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      queue: kibana-default

  - wait

  - command: .buildkite/pipelines/estf/pick_test_group_run_order.sh
    label: 'Pick Test Group Run Order'
    agents:
      queue: kibana-default
    env:
      FUNCTIONAL_MAX_MINUTES: 120
      LIMIT_CONFIG_TYPE: functional
      FTR_CONFIGS_DEPS: ""
      FTR_CONFIGS_RETRY_COUNT: 0
      FTR_CONFIG_PATTERNS: "test/functional/apps/**/*, x-pack/test/functional/apps/**/*"
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
    agents:
      queue: kibana-default