steps:
  - group: "Cloud Kibana Tests Group"
    key: "cktg"
    steps:
      - label: "Create Cloud Deployment"
        key: "create_cloud_deployment"
        command: .buildkite/scripts/steps/estf/cloud/create_cloud_deployment.sh
      - label: "Run Kibana Functional Tests"
        key: "run_kibana_tests"
        command: .buildkite/scripts/steps/estf/cloud/kibana_run_tests.sh
        depends_on: "create_cloud_deployment"
      - wait: ~
        continue_on_failure: true
      - label: "Delete Cloud Deployment"
        key: "delete_cloud_deployment"
        command: .buildkite/scripts/steps/estf/cloud/delete_cloud_deployment.sh
