steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      queue: kibana-default

  - wait

  - command: .buildkite/pipelines/estf/pick_test_group_run_order.sh
    label: 'Pick Test Groups Basic'
    agents:
      queue: kibana-default
    env:
      ESTF_UPLOAD_SCRIPT: ".buildkite/scripts/steps/estf/cloud/cloud_upload_steps.sh"
      TEST_TYPE: "basic"
      FUNCTIONAL_MAX_MINUTES: 60
      LIMIT_CONFIG_TYPE: functional
      FTR_CONFIGS_DEPS: ""
      FTR_CONFIGS_RETRY_COUNT: 0
      FTR_CONFIG_PATTERNS: "test/functional/apps/**/*"

  - command: .buildkite/pipelines/estf/pick_test_group_run_order.sh
    label: 'Pick Test Groups Xpack'
    agents:
      queue: kibana-default
    env:
      ESTF_UPLOAD_SCRIPT: ".buildkite/scripts/steps/estf/cloud/cloud_upload_steps.sh"
      TEST_TYPE: "xpack"
      FUNCTIONAL_MAX_MINUTES: 60
      LIMIT_CONFIG_TYPE: functional
      FTR_CONFIGS_DEPS: ""
      FTR_CONFIGS_RETRY_COUNT: 0
      FTR_CONFIG_PATTERNS: "x-pack/test/functional/apps/**/*"

  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
    agents:
      queue: kibana-default
