steps:
  - group: "Cloud Kibana Tests Group 1"
    key: "cktg1"
    steps:
      - label: "Create Cloud Deployment"
        key: "create_cloud_deployment1"
        command: .buildkite/scripts/steps/estf/cloud/create_cloud_deployment.sh
        agents:
          queue: n2-4
      - label: "Run Kibana Functional Tests"
        key: "run_kibana_tests1"
        command: .buildkite/scripts/steps/estf/cloud/run_kibana_tests.sh
        agents:
          queue: n2-4
        depends_on: "create_cloud_deployment1"
      - wait: ~
        continue_on_failure: true
      - label: "Delete Cloud Deployment"
        key: "delete_cloud_deployment1"
        command: .buildkite/scripts/steps/estf/cloud/shutdown_cloud_deployment.sh
        agents:
          queue: n2-4
  - group: "Cloud Kibana Tests Group 2"
    key: "cktg2"
    steps:
      - label: "Create Cloud Deployment"
        key: "create_cloud_deployment2"
        command: .buildkite/scripts/steps/estf/cloud/create_cloud_deployment.sh
        agents:
          queue: n2-4
      - label: "Run Kibana Functional Tests"
        key: "run_kibana_tests2"
        command: .buildkite/scripts/steps/estf/cloud/run_kibana_tests.sh
        agents:
          queue: n2-4
        depends_on: "create_cloud_deployment2"
      - wait: ~
        continue_on_failure: true
      - label: "Delete Cloud Deployment"
        key: "delete_cloud_deployment2"
        command: .buildkite/scripts/steps/estf/cloud/shutdown_cloud_deployment.sh
        agents:
          queue: n2-4