steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      queue: kibana-default

  - wait

  - command: .buildkite/scripts/steps/estf/ess/ess_kibana_testing.sh
    label: 'Visual Basic Tests ESS Kibana'
    agents:
      queue: n2-4
    env:
      ESTF_VISUAL_TESTS: true
      ESTF_META_ID: "basic-visual-tests"
      ESTF_PLAN_SETTINGS: "kibana_default.json"
      ESTF_KIBANA_TEST_TYPE: "basic"

  - command: .buildkite/scripts/steps/estf/ess/ess_kibana_testing.sh
    label: 'Visual Xpack Tests ESS Kibana'
    agents:
      queue: n2-4
    env:
      ESTF_VISUAL_TESTS: true
      ESTF_META_ID: "xpack-visual-tests"
      ESTF_PLAN_SETTINGS: "kibana_default.json"
      ESTF_KIBANA_TEST_TYPE: "xpack"

  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
    agents:
      queue: kibana-default
