steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      queue: kibana-default

  - wait

  - command: .buildkite/scripts/steps/estf/terraform/tf_kibana_os_testing.sh
    label: 'ubuntu-pro-2204-lts'
    agents:
      queue: n2-4
    env:
      ESTF_META_ID: "tf-kibana-os-ubuntu-pro-2204-lts"
      ESTF_KIBANA_OS_TEST: true
      AIT_PROVIDER: "gcp"
      AIT_USER: "buildkite-agent"
      AIT_IMAGE: "ubuntu-os-pro-cloud/ubuntu-pro-2204-lts"

  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
    agents:
      queue: kibana-default