steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      queue: kibana-default

  - wait

  - command: .buildkite/scripts/steps/estf/terraform/tf_stack_testing.sh
    label: 'TF Tests'
    agents:
      queue: n2-4
    env:
      ESTF_META_ID: "tf-stack-tests"
      ESTF_GITHUB_BRANCH: add-ansible-cloud-provider
      ESTF_GITHUB_OWNER: liza-mae
      AIT_PROVIDER: "gcp"
      AIT_USER: "liza"
    
  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
    agents:
      queue: kibana-default